export interface TradeFlow {
  year: number;
  month?: number;
  reporter: string; // ISO3
  partner: string;  // ISO3
  sectorId: string;
  hsCode: string;
  importValue: number; // USD
  exportValue: number; // USD
  importShare?: number; // percentage of reporter's total imports
  yoyChange?: number;  // year-over-year % change
}

export interface Economy {
  iso3: string;
  name: string;
  nameZh: string;
  region: string;
  lat: number;
  lng: number;
  role: "imposer" | "target" | "beneficiary" | "squeezed" | "neutral";
  narrative: string;
  narrativeZh: string;
  totalTradeWithUS: number; // USD billions, approximate
  shareChangeVsChina: number; // pp change in share of US imports, 2018–2025
}

export interface TariffEvent {
  date: string; // ISO 8601 date
  title: string;
  titleZh: string;
  description: string;
  descriptionZh: string;
  affectedEconomies: string[]; // ISO3[]
  affectedSectors: string[];
  tariffRate?: number; // percentage
  source: string;
  sourceUrl: string;
}

export interface Sector {
  id: string;
  label: string;
  labelZh: string;
  hsCodes: string[];
  description: string;
  descriptionZh: string;
  keyInsight: string;
  keyInsightZh: string;
}

export interface BriefingInsight {
  id: string;
  category: "share_shift" | "sector_move" | "taiwan_lens" | "trend_signal" | "anomaly";
  headline: string;
  headlineZh: string;
  body: string;
  bodyZh: string;
  metric: string;     // display string e.g. "+2.5pp"
  metricDirection: "up" | "down" | "neutral";
  relatedEconomies: string[]; // ISO3[]
  relatedSectors: string[];
  dataYear: number;
  isAutoGenerated: boolean;
}

export type AppLanguage = "en" | "zh";
