import { useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { useLanguage } from '../contexts/LanguageContext';
import type { BriefingInsight, Economy, TradeFlow, Sector } from '../types';

import SankeyDiagram  from '../components/Explore/SankeyDiagram';
import WorldMap       from '../components/Explore/WorldMap';
import SparklineMatrix from '../components/Explore/SparklineMatrix';

import rawBriefing  from '../data/briefing.json';
import rawEconomies from '../data/economies.json';
import rawFlows     from '../data/trade-flows.json';
import rawSectors   from '../data/sectors.json';

const briefing  = rawBriefing  as BriefingInsight[];
const economies = rawEconomies as Economy[];
const flows     = rawFlows     as TradeFlow[];
const sectors   = rawSectors   as Sector[];

// ── Category metadata ─────────────────────────────────────────────────────────

const CATEGORY_META: Record<
  BriefingInsight['category'],
  { labelEn: string; labelZh: string; color: string }
> = {
  share_shift:  { labelEn: 'Share Shift',   labelZh: '份額轉移',   color: '#622954' },
  sector_move:  { labelEn: 'Sector Move',   labelZh: '產業動態',   color: '#0070C0' },
  taiwan_lens:  { labelEn: 'Taiwan Lens',   labelZh: '台灣視角',   color: '#66327C' },
  trend_signal: { labelEn: 'Trend Signal',  labelZh: '趨勢訊號',   color: '#5DAC81' },
  anomaly:      { labelEn: 'Anomaly',       labelZh: '異常訊號',   color: '#F8B500' },
};

const ECONOMY_NAMES_EN: Record<string, string> = {
  CHN: 'China', VNM: 'Vietnam', IND: 'India',  TWN: 'Taiwan',
  THA: 'Thailand', MYS: 'Malaysia', MEX: 'Mexico', JPN: 'Japan',
  KOR: 'S.Korea', IDN: 'Indonesia', USA: 'U.S.',
};
const ECONOMY_NAMES_ZH: Record<string, string> = {
  CHN: '中國', VNM: '越南', IND: '印度', TWN: '台灣',
  THA: '泰國', MYS: '馬來西亞', MEX: '墨西哥', JPN: '日本',
  KOR: '韓國', IDN: '印尼', USA: '美國',
};

// ── Sorting helper ────────────────────────────────────────────────────────────

function insightSortKey(ins: BriefingInsight): number {
  // Curated first, then by direction magnitude
  const manual  = ins.isAutoGenerated ? 1 : 0;
  const dirScore = ins.metricDirection === 'neutral' ? 1 : 0;
  return manual * 100 + dirScore * 10;
}

// ── Sub-components ────────────────────────────────────────────────────────────

function StatCard({
  value,
  label,
  direction,
}: {
  value: string;
  label: string;
  direction: 'up' | 'down' | 'neutral';
}) {
  const color =
    direction === 'up'   ? '#5DAC81' :
    direction === 'down' ? '#C00000' :
    '#2E5C6E';

  return (
    <div
      style={{
        flex:             '1 1 160px',
        backgroundColor:  '#FCFAF2',
        border:           '1px solid rgba(112,124,116,0.3)',
        borderTop:        `3px solid ${color}`,
        borderRadius:     '4px',
        padding:          '14px 16px',
      }}
    >
      <div
        style={{
          fontFamily: '"JetBrains Mono", monospace',
          fontSize:   '26px',
          fontWeight: 700,
          color,
          lineHeight:  1,
          marginBottom: '6px',
        }}
      >
        {value}
      </div>
      <div
        style={{
          fontFamily: '"JetBrains Mono", monospace',
          fontSize:   '11px',
          color:      '#707C74',
          lineHeight:  1.4,
        }}
      >
        {label}
      </div>
    </div>
  );
}

function InsightCard({ insight }: { insight: BriefingInsight }) {
  const { language } = useLanguage();
  const [expanded, setExpanded] = useState(false);

  const meta      = CATEGORY_META[insight.category];
  const headline  = language === 'zh' ? insight.headlineZh : insight.headline;
  const body      = language === 'zh' ? insight.bodyZh : insight.body;
  const metricColor =
    insight.metricDirection === 'up'   ? '#5DAC81' :
    insight.metricDirection === 'down' ? '#C00000' :
    '#707C74';

  const econNames = insight.relatedEconomies
    .filter(e => e !== 'all')
    .map(e => language === 'zh' ? (ECONOMY_NAMES_ZH[e] ?? e) : (ECONOMY_NAMES_EN[e] ?? e));

  return (
    <div
      style={{
        backgroundColor: '#FCFAF2',
        border:          '1px solid rgba(112,124,116,0.25)',
        borderRadius:    '4px',
        padding:         '16px',
        display:         'flex',
        flexDirection:   'column',
        gap:             '8px',
      }}
    >
      {/* Top row: category badge + metric */}
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '8px' }}>
        <span
          style={{
            fontFamily:    '"JetBrains Mono", monospace',
            fontSize:      '9px',
            letterSpacing: '0.08em',
            color:         '#FCFAF2',
            backgroundColor: meta.color,
            padding:       '2px 7px',
            borderRadius:  '9999px',
            whiteSpace:    'nowrap',
          }}
        >
          {language === 'zh' ? meta.labelZh : meta.labelEn}
        </span>
        <span
          style={{
            fontFamily: '"JetBrains Mono", monospace',
            fontSize:   '18px',
            fontWeight:  700,
            color:       metricColor,
            whiteSpace:  'nowrap',
          }}
        >
          {insight.metric}
        </span>
      </div>

      {/* Headline */}
      <p
        style={{
          fontFamily:  '"Source Serif 4", serif',
          fontSize:    '14px',
          fontWeight:   600,
          color:        '#622954',
          lineHeight:   1.4,
          margin:       0,
        }}
      >
        {headline}
      </p>

      {/* Body (clipped unless expanded) */}
      <p
        style={{
          fontFamily:       '"Source Serif 4", serif',
          fontSize:         '13px',
          color:            '#343434',
          lineHeight:       1.65,
          margin:           0,
          overflow:         expanded ? 'visible' : 'hidden',
          display:          expanded ? 'block' : '-webkit-box',
          WebkitLineClamp:  expanded ? undefined : 4,
          WebkitBoxOrient:  'vertical' as React.CSSProperties['WebkitBoxOrient'],
        }}
      >
        {body}
      </p>

      {/* Expand toggle */}
      <button
        onClick={() => setExpanded(e => !e)}
        style={{
          fontFamily:      '"JetBrains Mono", monospace',
          fontSize:        '10px',
          color:           '#0070C0',
          background:      'none',
          border:          'none',
          padding:         '0',
          cursor:          'pointer',
          textAlign:       'left',
          alignSelf:       'flex-start',
        }}
      >
        {expanded
          ? (language === 'zh' ? '收起' : 'Show less')
          : (language === 'zh' ? '展開全文' : 'Read more')}
      </button>

      {/* Economy chips */}
      {econNames.length > 0 && (
        <div style={{ display: 'flex', flexWrap: 'wrap', gap: '4px', marginTop: '2px' }}>
          {econNames.map((name, i) => (
            <span
              key={i}
              style={{
                fontFamily:      '"JetBrains Mono", monospace',
                fontSize:        '9px',
                color:           '#2E5C6E',
                border:          '1px solid rgba(46,92,110,0.35)',
                borderRadius:    '9999px',
                padding:         '1px 6px',
                whiteSpace:      'nowrap',
              }}
            >
              {name}
            </span>
          ))}
        </div>
      )}

      {/* Data year */}
      <div
        style={{
          fontFamily: '"JetBrains Mono", monospace',
          fontSize:   '9px',
          color:      '#707C74',
          marginTop:  '2px',
        }}
      >
        {insight.dataYear} · {insight.isAutoGenerated ? 'UN Comtrade' : 'Curated analysis'}
      </div>
    </div>
  );
}

function SectionHeader({
  tag,
  titleEn,
  titleZh,
  subtitleEn,
  subtitleZh,
}: {
  tag: string;
  titleEn: string;
  titleZh: string;
  subtitleEn: string;
  subtitleZh: string;
}) {
  const { language } = useLanguage();
  return (
    <div style={{ marginBottom: '28px' }}>
      <span
        style={{
          fontFamily:    '"JetBrains Mono", monospace',
          fontSize:      '10px',
          letterSpacing: '0.12em',
          color:         '#707C74',
          display:       'block',
          marginBottom:  '6px',
        }}
      >
        {tag}
      </span>
      <h2
        style={{
          fontFamily:   '"Source Serif 4", serif',
          fontSize:     'clamp(20px, 3vw, 28px)',
          fontWeight:    600,
          color:         '#622954',
          margin:        '0 0 8px',
          lineHeight:    1.2,
        }}
      >
        {language === 'zh' ? titleZh : titleEn}
      </h2>
      <p
        style={{
          fontFamily: '"Source Serif 4", serif',
          fontSize:   '14px',
          color:      '#2E5C6E',
          margin:     0,
          lineHeight: 1.6,
          maxWidth:   '640px',
        }}
      >
        {language === 'zh' ? subtitleZh : subtitleEn}
      </p>
    </div>
  );
}

// ── Tariff event timeline row ─────────────────────────────────────────────────

import type { TariffEvent } from '../types';
import rawTariffEvents from '../data/tariff-events.json';
const tariffEvents = rawTariffEvents as TariffEvent[];

function TariffEventRow({ event }: { event: TariffEvent }) {
  const { language } = useLanguage();
  const title = language === 'zh' ? event.titleZh : event.title;
  const desc  = language === 'zh' ? event.descriptionZh : event.description;

  return (
    <div
      style={{
        display:      'grid',
        gridTemplateColumns: '90px 1fr',
        gap:          '0 16px',
        paddingBottom: '20px',
        borderBottom: '1px solid rgba(112,124,116,0.15)',
        marginBottom: '0',
      }}
    >
      {/* Date column */}
      <div style={{ paddingTop: '2px' }}>
        <div
          style={{
            fontFamily: '"JetBrains Mono", monospace',
            fontSize:   '10px',
            color:      '#707C74',
          }}
        >
          {event.date}
        </div>
        {event.tariffRate !== undefined && (
          <div
            style={{
              fontFamily: '"JetBrains Mono", monospace',
              fontSize:   '13px',
              fontWeight:  700,
              color:       '#C00000',
              marginTop:   '2px',
            }}
          >
            {event.tariffRate}%
          </div>
        )}
      </div>

      {/* Content column */}
      <div>
        <div
          style={{
            fontFamily: '"Source Serif 4", serif',
            fontSize:   '13px',
            fontWeight:  600,
            color:       '#343434',
            marginBottom: '4px',
          }}
        >
          {title}
        </div>
        <div
          style={{
            fontFamily: '"Source Serif 4", serif',
            fontSize:   '12px',
            color:      '#2E5C6E',
            lineHeight:  1.6,
          }}
        >
          {desc}
        </div>
        <a
          href={event.sourceUrl}
          target="_blank"
          rel="noopener noreferrer"
          style={{
            fontFamily:     '"JetBrains Mono", monospace',
            fontSize:       '9px',
            color:          '#707C74',
            textDecoration: 'none',
            borderBottom:   '1px solid rgba(112,124,116,0.3)',
            display:        'inline-block',
            marginTop:      '4px',
          }}
        >
          {event.source} ↗
        </a>
      </div>
    </div>
  );
}

// ── Main component ────────────────────────────────────────────────────────────

export default function Landing() {
  const { language } = useLanguage();

  // ── Computed stats from data ──────────────────────────────────────────────

  const stats = useMemo(() => {
    const tracked = economies.filter(e => e.iso3 !== 'USA' && e.iso3 !== 'EUN');

    const china = tracked.find(e => e.iso3 === 'CHN');
    const chinaChange = china?.shareChangeVsChina ?? 0;

    const aseanCodes = ['VNM', 'THA', 'MYS', 'IDN'];
    const aseanGain  = tracked
      .filter(e => aseanCodes.includes(e.iso3))
      .reduce((s, e) => s + e.shareChangeVsChina, 0);

    const largGainer = tracked
      .filter(e => e.shareChangeVsChina > 0)
      .reduce((max, e) => e.shareChangeVsChina > max.shareChangeVsChina ? e : max, tracked[0]!);

    const gainCount = tracked.filter(e => e.shareChangeVsChina > 0).length;

    return { chinaChange, aseanGain, largGainer, gainCount, tracked: tracked.length };
  }, []);

  // ── Sorted insights ───────────────────────────────────────────────────────

  const sortedInsights = useMemo(
    () => [...briefing].sort((a, b) => insightSortKey(a) - insightSortKey(b)),
    [],
  );

  // ── Layout helpers ────────────────────────────────────────────────────────

  const sectionStyle: React.CSSProperties = {
    paddingTop:    '56px',
    paddingBottom: '56px',
  };

  const divider: React.CSSProperties = {
    borderTop:   '1px solid rgba(112,124,116,0.2)',
    margin:      '0',
  };

  return (
    <div style={{ backgroundColor: '#FCFAF2' }}>

      {/* ══════════════════════════════════════════════════════════════
          LAYER 1 — BRIEFING
      ══════════════════════════════════════════════════════════════ */}
      <section style={sectionStyle}>

        {/* Edition header */}
        <div style={{ marginBottom: '32px' }}>
          <span
            style={{
              fontFamily:    '"JetBrains Mono", monospace',
              fontSize:      '10px',
              letterSpacing: '0.12em',
              color:         '#707C74',
            }}
          >
            {language === 'zh' ? '全球貿易衝擊監測站 · 2026年3月版' : 'GLOBAL TRADE SHOCK MONITOR · MARCH 2026 EDITION'}
          </span>
          <h1
            style={{
              fontFamily: '"Source Serif 4", serif',
              fontSize:   'clamp(24px, 4vw, 38px)',
              fontWeight:  600,
              color:       '#622954',
              margin:      '10px 0 12px',
              lineHeight:  1.2,
            }}
          >
            {language === 'zh'
              ? '美國關稅衝擊正在重塑全球供應鏈'
              : 'U.S. tariffs are redrawing the map of global trade'}
          </h1>
          <p
            style={{
              fontFamily: '"Source Serif 4", serif',
              fontSize:   '16px',
              color:      '#2E5C6E',
              maxWidth:   '680px',
              lineHeight:  1.7,
              margin:     0,
            }}
          >
            {language === 'zh'
              ? '追蹤2018至2025年間，美中貿易摩擦如何將供應鏈從中國轉移至越南、台灣、印度及東南亞各國——以及哪些受益者開始流失優勢。'
              : 'Tracking how the U.S.-China trade war has shifted supply chains away from China toward Vietnam, Taiwan, India and Southeast Asia—and which beneficiaries are already starting to slip.'}
          </p>
        </div>

        {/* Stat strip */}
        <div
          style={{
            display:        'flex',
            flexWrap:       'wrap',
            gap:            '12px',
            marginBottom:   '40px',
          }}
        >
          <StatCard
            value={`${stats.chinaChange.toFixed(1)}pp`}
            label={language === 'zh' ? '中國進口市佔跌幅（2018–2024）' : "China's import share change (2018–2024)"}
            direction="down"
          />
          <StatCard
            value={`+${stats.aseanGain.toFixed(1)}pp`}
            label={language === 'zh' ? '東協四國合計市佔增幅' : 'ASEAN-4 combined share gain'}
            direction="up"
          />
          <StatCard
            value={`+${stats.largGainer.shareChangeVsChina.toFixed(1)}pp`}
            label={
              language === 'zh'
                ? `最大單一受益者：${stats.largGainer.nameZh}`
                : `Largest single gainer: ${stats.largGainer.name}`
            }
            direction="up"
          />
          <StatCard
            value={`${stats.gainCount}/${stats.tracked}`}
            label={language === 'zh' ? '追蹤經濟體中市佔增加者' : 'tracked economies gained share'}
            direction="neutral"
          />
        </div>

        {/* Insight cards */}
        <div
          style={{
            display:             'grid',
            gridTemplateColumns: 'repeat(auto-fill, minmax(300px, 1fr))',
            gap:                 '16px',
            marginBottom:        '40px',
          }}
        >
          {sortedInsights.map(ins => (
            <InsightCard key={ins.id} insight={ins} />
          ))}
        </div>

        {/* Scroll prompt */}
        <div style={{ textAlign: 'center', paddingTop: '8px' }}>
          <button
            onClick={() =>
              document.getElementById('explore')?.scrollIntoView({ behavior: 'smooth' })
            }
            style={{
              fontFamily:      '"JetBrains Mono", monospace',
              fontSize:        '12px',
              color:           '#0070C0',
              background:      'none',
              border:          '1px solid rgba(0,112,192,0.4)',
              borderRadius:    '4px',
              padding:         '8px 20px',
              cursor:          'pointer',
              letterSpacing:   '0.05em',
            }}
          >
            {language === 'zh' ? '↓ 探索數據流向' : '↓ Explore the data flows'}
          </button>
        </div>
      </section>

      <hr style={divider} />

      {/* ══════════════════════════════════════════════════════════════
          LAYER 2 — EXPLORE (id="explore")
      ══════════════════════════════════════════════════════════════ */}
      <section id="explore" style={sectionStyle}>

        <SectionHeader
          tag={language === 'zh' ? '探索 · 貿易流向' : 'EXPLORE · TRADE FLOWS'}
          titleEn="Where did the trade go?"
          titleZh="貿易流向了哪裡？"
          subtitleEn="The Sankey diagram shows how U.S. import value is distributed across sectors and economies for the selected year. The map shows net share gains and losses vs China since 2018."
          subtitleZh="左圖顯示特定年份美國進口金額在各產業與經濟體間的分布；右圖以顏色深淺呈現各國相對於中國的市佔增減幅度。"
        />

        {/* Sankey + Map: two-column on large screens */}
        <div
          style={{
            display:             'grid',
            gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))',
            gap:                 '32px',
            alignItems:          'start',
          }}
        >
          {/* Sankey */}
          <div>
            <h3
              style={{
                fontFamily:   '"Source Serif 4", serif',
                fontSize:     '14px',
                fontWeight:    600,
                color:         '#2E5C6E',
                margin:        '0 0 12px',
                letterSpacing: '0.02em',
              }}
            >
              {language === 'zh' ? '貿易流向圖（Sankey）' : 'Trade Flow (Sankey)'}
            </h3>
            <SankeyDiagram flows={flows} sectors={sectors} />
          </div>

          {/* World map */}
          <div>
            <h3
              style={{
                fontFamily:   '"Source Serif 4", serif',
                fontSize:     '14px',
                fontWeight:    600,
                color:         '#2E5C6E',
                margin:        '0 0 12px',
                letterSpacing: '0.02em',
              }}
            >
              {language === 'zh' ? '市佔變化地圖（vs 中國）' : 'Import Share Change vs China'}
            </h3>
            <WorldMap economies={economies} />
          </div>
        </div>

        {/* Sector cards */}
        <div style={{ marginTop: '48px' }}>
          <h3
            style={{
              fontFamily:   '"Source Serif 4", serif',
              fontSize:     '18px',
              fontWeight:    600,
              color:         '#622954',
              margin:        '0 0 20px',
            }}
          >
            {language === 'zh' ? '重點產業' : 'Sector Briefs'}
          </h3>
          <div
            style={{
              display:             'grid',
              gridTemplateColumns: 'repeat(auto-fill, minmax(260px, 1fr))',
              gap:                 '14px',
            }}
          >
            {sectors.map(s => (
              <Link
                key={s.id}
                to={`/sectors/${s.id}`}
                style={{ textDecoration: 'none' }}
              >
                <div
                  style={{
                    backgroundColor: '#FCFAF2',
                    border:          '1px solid rgba(112,124,116,0.25)',
                    borderRadius:    '4px',
                    padding:         '14px 16px',
                    cursor:          'pointer',
                    transition:      'border-color 0.15s',
                  }}
                  onMouseOver={e =>
                    ((e.currentTarget as HTMLDivElement).style.borderColor = 'rgba(0,112,192,0.5)')
                  }
                  onMouseOut={e =>
                    ((e.currentTarget as HTMLDivElement).style.borderColor = 'rgba(112,124,116,0.25)')
                  }
                >
                  <div
                    style={{
                      fontFamily:   '"Source Serif 4", serif',
                      fontSize:     '13px',
                      fontWeight:    600,
                      color:         '#343434',
                      marginBottom:  '6px',
                    }}
                  >
                    {language === 'zh' ? s.labelZh : s.label}
                  </div>
                  <div
                    style={{
                      fontFamily: '"Source Serif 4", serif',
                      fontSize:   '12px',
                      color:      '#2E5C6E',
                      lineHeight:  1.55,
                    }}
                  >
                    {language === 'zh' ? s.keyInsightZh : s.keyInsight}
                  </div>
                  <div
                    style={{
                      fontFamily:  '"JetBrains Mono", monospace',
                      fontSize:    '10px',
                      color:       '#0070C0',
                      marginTop:   '8px',
                    }}
                  >
                    {language === 'zh' ? '查看詳情 →' : 'Explore →'}
                  </div>
                </div>
              </Link>
            ))}
          </div>
        </div>
      </section>

      <hr style={divider} />

      {/* ══════════════════════════════════════════════════════════════
          LAYER 3 — ECONOMIES (id="economies")
      ══════════════════════════════════════════════════════════════ */}
      <section id="economies" style={sectionStyle}>

        <SectionHeader
          tag={language === 'zh' ? '經濟體 · 追蹤器' : 'ECONOMIES · TRACKER'}
          titleEn="Economy-by-economy breakdown"
          titleZh="逐一經濟體追蹤"
          subtitleEn="Each cell shows how U.S. imports from that economy in that sector trended from 2018 to 2024. Sparklines are independently scaled; the value shown is the 2024 import total."
          subtitleZh="每格顯示美國自該經濟體於各產業的進口走勢（2018–2024）。折線圖各自獨立縮放；數值為2024年進口總額。"
        />

        <SparklineMatrix flows={flows} sectors={sectors} />

        {/* Economy quick-links */}
        <div
          style={{
            display:             'grid',
            gridTemplateColumns: 'repeat(auto-fill, minmax(200px, 1fr))',
            gap:                 '10px',
            marginTop:           '32px',
          }}
        >
          {economies
            .filter(e => e.iso3 !== 'USA' && e.iso3 !== 'EUN')
            .sort((a, b) => b.shareChangeVsChina - a.shareChangeVsChina)
            .map(e => {
              const change    = e.shareChangeVsChina;
              const sign      = change >= 0 ? '+' : '';
              const color     = change > 0 ? '#5DAC81' : change < 0 ? '#C00000' : '#707C74';
              const roleBadge: Record<Economy['role'], { en: string; zh: string }> = {
                imposer:     { en: 'Imposer',     zh: '發動方' },
                target:      { en: 'Target',      zh: '目標方' },
                beneficiary: { en: 'Beneficiary', zh: '受益方' },
                squeezed:    { en: 'Squeezed',    zh: '夾縫方' },
                neutral:     { en: 'Neutral',     zh: '中立方' },
              };
              return (
                <Link
                  key={e.iso3}
                  to={`/economies/${e.iso3}`}
                  style={{ textDecoration: 'none' }}
                >
                  <div
                    style={{
                      backgroundColor: '#FCFAF2',
                      border:          '1px solid rgba(112,124,116,0.25)',
                      borderRadius:    '4px',
                      padding:         '10px 14px',
                      cursor:          'pointer',
                      transition:      'border-color 0.15s',
                    }}
                    onMouseOver={e2 =>
                      ((e2.currentTarget as HTMLDivElement).style.borderColor = 'rgba(0,112,192,0.5)')
                    }
                    onMouseOut={e2 =>
                      ((e2.currentTarget as HTMLDivElement).style.borderColor = 'rgba(112,124,116,0.25)')
                    }
                  >
                    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'baseline' }}>
                      <span
                        style={{
                          fontFamily: '"Source Serif 4", serif',
                          fontSize:   '13px',
                          fontWeight:  600,
                          color:       '#343434',
                        }}
                      >
                        {language === 'zh' ? e.nameZh : e.name}
                      </span>
                      <span
                        style={{
                          fontFamily: '"JetBrains Mono", monospace',
                          fontSize:   '13px',
                          fontWeight:  700,
                          color,
                        }}
                      >
                        {sign}{change.toFixed(1)}pp
                      </span>
                    </div>
                    <div
                      style={{
                        fontFamily:  '"JetBrains Mono", monospace',
                        fontSize:    '9px',
                        color:       '#707C74',
                        marginTop:   '2px',
                      }}
                    >
                      {roleBadge[e.role][language === 'zh' ? 'zh' : 'en']}
                    </div>
                  </div>
                </Link>
              );
            })}
        </div>
      </section>

      <hr style={divider} />

      {/* ══════════════════════════════════════════════════════════════
          TARIFF TIMELINE (inline, compact)
      ══════════════════════════════════════════════════════════════ */}
      <section style={{ ...sectionStyle, paddingBottom: '64px' }}>
        <SectionHeader
          tag={language === 'zh' ? '政策時間軸 · 關稅事件' : 'POLICY TIMELINE · TARIFF EVENTS'}
          titleEn="Key tariff milestones"
          titleZh="關鍵關稅里程碑"
          subtitleEn="Major U.S. tariff actions and bilateral trade agreements, 2018–2025. Each event links to its official source."
          subtitleZh="2018至2025年美國主要關稅行動與雙邊貿易協議，每項均附官方來源連結。"
        />

        <div style={{ display: 'flex', flexDirection: 'column', gap: '20px', maxWidth: '760px' }}>
          {[...tariffEvents]
            .sort((a, b) => a.date.localeCompare(b.date))
            .map(event => (
              <TariffEventRow key={event.date} event={event} />
            ))}
        </div>

        <div style={{ marginTop: '20px' }}>
          <Link
            to="/timeline"
            style={{
              fontFamily:     '"JetBrains Mono", monospace',
              fontSize:       '12px',
              color:          '#0070C0',
              textDecoration: 'none',
              borderBottom:   '1px solid rgba(0,112,192,0.4)',
              paddingBottom:  '1px',
            }}
          >
            {language === 'zh' ? '→ 查看完整時間軸' : '→ Full timeline page'}
          </Link>
        </div>
      </section>

    </div>
  );
}
