#!/usr/bin/env tsx
/**
 * UN Comtrade Data Pipeline
 *
 * Fetches annual U.S. import data for key trade partners and sectors,
 * writes results to src/data/, and generates BriefingInsight objects.
 *
 * Usage:
 *   npm run update-data
 *   COMTRADE_API_KEY=your_key npm run update-data
 *
 * Rate limits: 1 req/sec enforced, hard stop at 480 req/run (under 500/day cap).
 */

import * as fs from 'fs';
import * as path from 'path';

// ── Inline types (mirrors src/types/index.ts — keep in sync) ──────────────────

interface TradeFlow {
  year: number;
  month?: number;
  reporter: string;
  partner: string;
  sectorId: string;
  hsCode: string;
  importValue: number;
  exportValue: number;
  importShare?: number;
  yoyChange?: number;
}

interface Economy {
  iso3: string;
  name: string;
  nameZh: string;
  region: string;
  lat: number;
  lng: number;
  role: 'imposer' | 'target' | 'beneficiary' | 'squeezed' | 'neutral';
  narrative: string;
  narrativeZh: string;
  totalTradeWithUS: number;
  shareChangeVsChina: number;
}

interface BriefingInsight {
  id: string;
  category: 'share_shift' | 'sector_move' | 'taiwan_lens' | 'trend_signal' | 'anomaly';
  headline: string;
  headlineZh: string;
  body: string;
  bodyZh: string;
  metric: string;
  metricDirection: 'up' | 'down' | 'neutral';
  relatedEconomies: string[];
  relatedSectors: string[];
  dataYear: number;
  isAutoGenerated: boolean;
}

// ── Constants ──────────────────────────────────────────────────────────────────

const REPORTER_CODE = '842';
const REPORTER_ISO3 = 'USA';

/** Comtrade numeric partner code → ISO3 */
const PARTNERS: Record<string, string> = {
  '156': 'CHN',
  '704': 'VNM',
  '699': 'IND',
  '490': 'TWN',
  '764': 'THA',
  '458': 'MYS',
  '484': 'MEX',
  '392': 'JPN',
  '410': 'KOR',
  '360': 'IDN',
};

const SECTORS: Record<string, { label: string; hsCodes: string[] }> = {
  semiconductors: {
    label: 'Semiconductors & Electronics',
    hsCodes: ['8541', '8542', '8471', '8473'],
  },
  smartphones: {
    label: 'Smartphones & Consumer Electronics',
    hsCodes: ['8517'],
  },
  'ev-battery': {
    label: 'EVs & Battery Chain',
    hsCodes: ['8703', '8507', '8504'],
  },
  textiles: {
    label: 'Textiles & Light Manufacturing',
    hsCodes: ['61', '62', '64', '42'],
  },
};

const YEARS = ['2018', '2019', '2020', '2021', '2022', '2023', '2024', '2025'];
const API_BASE = 'https://comtradeapi.un.org/data/v1/get/C/A/HS';
const DELAY_MS = 1500;
const REQUEST_LIMIT = 480; // stay below 500/day hard cap

// Display names used in auto-generated insight text
const ECONOMY_NAMES: Record<string, string> = {
  CHN: 'China', VNM: 'Vietnam', IND: 'India', TWN: 'Taiwan',
  THA: 'Thailand', MYS: 'Malaysia', MEX: 'Mexico', JPN: 'Japan',
  KOR: 'South Korea', IDN: 'Indonesia', USA: 'United States',
};
const ECONOMY_NAMES_ZH: Record<string, string> = {
  CHN: '中國', VNM: '越南', IND: '印度', TWN: '台灣',
  THA: '泰國', MYS: '馬來西亞', MEX: '墨西哥', JPN: '日本',
  KOR: '韓國', IDN: '印尼', USA: '美國',
};
const SECTOR_LABELS: Record<string, string> = {
  semiconductors: 'semiconductor',
  smartphones: 'smartphone',
  'ev-battery': 'EV & battery',
  textiles: 'textile',
};
const SECTOR_LABELS_ZH: Record<string, string> = {
  semiconductors: '半導體',
  smartphones: '智慧型手機',
  'ev-battery': '電動車與電池',
  textiles: '紡織',
};

// ── File paths ─────────────────────────────────────────────────────────────────

const ROOT = process.cwd();
const DATA_DIR = path.join(ROOT, 'src', 'data');
const SCRIPTS_DIR = path.join(ROOT, 'scripts');
const TRADE_FLOWS_PATH = path.join(DATA_DIR, 'trade-flows.json');
const ECONOMIES_PATH = path.join(DATA_DIR, 'economies.json');
const BRIEFING_PATH = path.join(DATA_DIR, 'briefing.json');
const FALLBACK_PATH = path.join(SCRIPTS_DIR, 'fallback-data.json');

// ── I/O helpers ────────────────────────────────────────────────────────────────

function readJson<T>(filePath: string, fallback: T): T {
  try {
    return JSON.parse(fs.readFileSync(filePath, 'utf-8')) as T;
  } catch {
    return fallback;
  }
}

function writeJson(filePath: string, data: unknown): void {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, JSON.stringify(data, null, 2) + '\n', 'utf-8');
}

function sleep(ms: number): Promise<void> {
  return new Promise(resolve => setTimeout(resolve, ms));
}

// ── Comtrade API ───────────────────────────────────────────────────────────────

interface ComtradeRecord {
  period: string;
  reporterCode: number;
  partnerCode: number;
  cmdCode: string;
  flowCode: string;
  primaryValue: number;
  netWgt?: number;
}

interface ComtradeResponse {
  data?: ComtradeRecord[];
  count?: number;
  message?: string[];
  error?: string;
}

/** Extracts "Try again in N seconds" from a 429 response body, returns ms to wait. */
function parseRetryAfterMs(body: string): number {
  const match = /try again in (\d+) second/i.exec(body);
  const seconds = match ? parseInt(match[1]!, 10) : 20;
  return (seconds + 2) * 1000; // add 2s buffer
}

async function fetchComtrade(
  partnerCode: string,
  cmdCodes: string[],
  year: string,
  apiKey: string,
  attempt = 1,
): Promise<ComtradeRecord[]> {
  const params = new URLSearchParams({
    reporterCode: REPORTER_CODE,
    partnerCode,
    cmdCode: cmdCodes.join(','),
    flowCode: 'M',
    period: year,
  });

  const url = `${API_BASE}?${params.toString()}`;

  const response = await fetch(url, {
    headers: { 'Ocp-Apim-Subscription-Key': apiKey },
    signal: AbortSignal.timeout(30_000),
  });

  if (response.status === 429) {
    if (attempt > 3) throw new Error(`HTTP 429: rate limit exceeded after 3 retries`);
    const body = await response.text().catch(() => '');
    const waitMs = parseRetryAfterMs(body);
    console.log(`    ⏳ Rate limited — waiting ${Math.round(waitMs / 1000)}s (attempt ${attempt}/3)…`);
    await sleep(waitMs);
    return fetchComtrade(partnerCode, cmdCodes, year, apiKey, attempt + 1);
  }

  if (!response.ok) {
    const body = await response.text().catch(() => '');
    throw new Error(`HTTP ${response.status}${body ? `: ${body.slice(0, 200)}` : ''}`);
  }

  const json = (await response.json()) as ComtradeResponse;
  if (json.error) throw new Error(json.error);

  return json.data ?? [];
}

// ── Transform ──────────────────────────────────────────────────────────────────

function toTradeFlows(
  records: ComtradeRecord[],
  sectorId: string,
  iso3: string,
): TradeFlow[] {
  return records
    .filter(r => r.primaryValue > 0)
    .map(r => ({
      year: parseInt(r.period, 10),
      reporter: REPORTER_ISO3,
      partner: iso3,
      sectorId,
      hsCode: r.cmdCode,
      importValue: r.primaryValue,
      exportValue: 0, // pipeline fetches M (imports) only
    }));
}

// ── Enrichment: importShare + yoyChange ────────────────────────────────────────

function enrichFlows(flows: TradeFlow[]): TradeFlow[] {
  // Total imports per year+sector across all partners
  const sectorYearTotal = new Map<string, number>();
  for (const f of flows) {
    const k = `${f.year}:${f.sectorId}`;
    sectorYearTotal.set(k, (sectorYearTotal.get(k) ?? 0) + f.importValue);
  }

  // Per-record lookup for previous-year value (same partner+sector+hsCode)
  const recordLookup = new Map<string, number>();
  for (const f of flows) {
    recordLookup.set(`${f.partner}:${f.sectorId}:${f.hsCode}:${f.year}`, f.importValue);
  }

  return flows.map(f => {
    const sectorTotal = sectorYearTotal.get(`${f.year}:${f.sectorId}`) ?? 0;
    const importShare = sectorTotal > 0 ? (f.importValue / sectorTotal) * 100 : undefined;

    const prevValue = recordLookup.get(`${f.partner}:${f.sectorId}:${f.hsCode}:${f.year - 1}`);
    const yoyChange =
      prevValue != null && prevValue > 0
        ? ((f.importValue - prevValue) / prevValue) * 100
        : undefined;

    return { ...f, importShare, yoyChange };
  });
}

// ── Economy update ─────────────────────────────────────────────────────────────

function updateEconomies(flows: TradeFlow[]): void {
  const economies = readJson<Economy[]>(ECONOMIES_PATH, []);
  if (economies.length === 0) return;

  const allYears = [...new Set(flows.map(f => f.year))].sort((a, b) => a - b);
  const latestYear = allYears[allYears.length - 1];
  const baseYear = allYears.includes(2018) ? 2018 : allYears[0];

  // Grand totals per year (sum across all partners + sectors in dataset)
  const grandTotal = new Map<number, number>();
  for (const f of flows) {
    grandTotal.set(f.year, (grandTotal.get(f.year) ?? 0) + f.importValue);
  }

  // Per-partner total per year
  const partnerTotal = new Map<string, number>();
  for (const f of flows) {
    const k = `${f.partner}:${f.year}`;
    partnerTotal.set(k, (partnerTotal.get(k) ?? 0) + f.importValue);
  }

  const grandBase = grandTotal.get(baseYear) ?? 0;
  const grandLatest = grandTotal.get(latestYear) ?? 0;

  const updated = economies.map(e => {
    // totalTradeWithUS from latest year data (USD billions, 1 decimal)
    const raw = partnerTotal.get(`${e.iso3}:${latestYear}`);
    const totalTradeWithUS =
      raw != null ? Math.round((raw / 1e9) * 10) / 10 : e.totalTradeWithUS;

    // shareChangeVsChina = this economy's pp shift in share from base to latest
    const shareBase =
      grandBase > 0
        ? ((partnerTotal.get(`${e.iso3}:${baseYear}`) ?? 0) / grandBase) * 100
        : 0;
    const shareLatest =
      grandLatest > 0
        ? ((partnerTotal.get(`${e.iso3}:${latestYear}`) ?? 0) / grandLatest) * 100
        : 0;
    const shareChangeVsChina =
      grandBase > 0 && grandLatest > 0
        ? Math.round((shareLatest - shareBase) * 100) / 100
        : e.shareChangeVsChina;

    return { ...e, totalTradeWithUS, shareChangeVsChina };
  });

  writeJson(ECONOMIES_PATH, updated);
  console.log('  ✓ Updated economies.json');
}

// ── Insight generation ─────────────────────────────────────────────────────────

function generateInsights(flows: TradeFlow[]): BriefingInsight[] {
  if (flows.length === 0) return [];

  const insights: BriefingInsight[] = [];

  const allYears = [...new Set(flows.map(f => f.year))].sort((a, b) => a - b);
  const latestYear = allYears[allYears.length - 1];
  const baseYear = allYears.includes(2018) ? 2018 : allYears[0];

  // ── Aggregation maps ───────────────────────────────────────────────────────
  const grandYearTotal = new Map<number, number>();
  const partnerYearTotal = new Map<string, number>();
  const partnerSectorYearTotal = new Map<string, number>();
  const sectorYearTotal = new Map<string, number>();

  for (const f of flows) {
    grandYearTotal.set(f.year, (grandYearTotal.get(f.year) ?? 0) + f.importValue);
    partnerYearTotal.set(
      `${f.partner}:${f.year}`,
      (partnerYearTotal.get(`${f.partner}:${f.year}`) ?? 0) + f.importValue,
    );
    partnerSectorYearTotal.set(
      `${f.partner}:${f.sectorId}:${f.year}`,
      (partnerSectorYearTotal.get(`${f.partner}:${f.sectorId}:${f.year}`) ?? 0) + f.importValue,
    );
    sectorYearTotal.set(
      `${f.sectorId}:${f.year}`,
      (sectorYearTotal.get(`${f.sectorId}:${f.year}`) ?? 0) + f.importValue,
    );
  }

  const grandBase = grandYearTotal.get(baseYear) ?? 0;
  const grandLatest = grandYearTotal.get(latestYear) ?? 0;
  if (grandBase === 0 || grandLatest === 0) return [];

  const overallShare = (iso3: string, year: number) =>
    ((partnerYearTotal.get(`${iso3}:${year}`) ?? 0) / (grandYearTotal.get(year) ?? 1)) * 100;

  const sectorShare = (iso3: string, sectorId: string, year: number) =>
    ((partnerSectorYearTotal.get(`${iso3}:${sectorId}:${year}`) ?? 0) /
      (sectorYearTotal.get(`${sectorId}:${year}`) ?? 1)) *
    100;

  const psvt = (iso3: string, sectorId: string, year: number) =>
    partnerSectorYearTotal.get(`${iso3}:${sectorId}:${year}`) ?? 0;

  // 1. Share shift: overall import share change ≥ 1.0pp
  for (const iso3 of Object.values(PARTNERS)) {
    const shareBase = overallShare(iso3, baseYear);
    const shareLatest = overallShare(iso3, latestYear);
    const pp = shareLatest - shareBase;
    if (Math.abs(pp) < 1.0 || shareBase === 0) continue;

    const dir = pp > 0 ? ('up' as const) : ('down' as const);
    const verb = pp > 0 ? 'rose' : 'fell';
    const zhVerb = pp > 0 ? '上升' : '下降';

    insights.push({
      id: `auto-share-${iso3.toLowerCase()}-${latestYear}`,
      category: 'share_shift',
      headline: `${ECONOMY_NAMES[iso3] ?? iso3}'s share of U.S. imports ${verb} by ${Math.abs(pp).toFixed(1)}pp (${baseYear}–${latestYear})`,
      headlineZh: `${ECONOMY_NAMES_ZH[iso3] ?? iso3}在美國進口市佔率自${baseYear}年${zhVerb}${Math.abs(pp).toFixed(1)}個百分點`,
      body: `${ECONOMY_NAMES[iso3] ?? iso3}'s share of tracked U.S. goods imports moved from ${shareBase.toFixed(1)}% in ${baseYear} to ${shareLatest.toFixed(1)}% in ${latestYear} (${pp >= 0 ? '+' : ''}${pp.toFixed(1)}pp). Source: UN Comtrade.`,
      bodyZh: `${ECONOMY_NAMES_ZH[iso3] ?? iso3}在美國受追蹤商品進口中的佔比自${baseYear}年${shareBase.toFixed(1)}%${zhVerb}至${latestYear}年${shareLatest.toFixed(1)}%（${pp >= 0 ? '+' : ''}${pp.toFixed(1)}pp）。資料來源：聯合國商品貿易統計資料庫。`,
      metric: `${pp >= 0 ? '+' : ''}${pp.toFixed(1)}pp`,
      metricDirection: dir,
      relatedEconomies: [iso3],
      relatedSectors: ['all'],
      dataYear: latestYear,
      isAutoGenerated: true,
    });
  }

  // 2. Sector-specific YoY move ≥ 20%
  const priorYear = latestYear - 1;
  for (const iso3 of Object.values(PARTNERS)) {
    for (const sectorId of Object.keys(SECTORS)) {
      const latest = psvt(iso3, sectorId, latestYear);
      const prior = psvt(iso3, sectorId, priorYear);
      if (prior === 0 || latest === 0) continue;
      const yoy = ((latest - prior) / prior) * 100;
      if (Math.abs(yoy) < 20) continue;

      const dir = yoy > 0 ? ('up' as const) : ('down' as const);
      const verb = yoy > 0 ? 'grew' : 'fell';
      const zhVerb = yoy > 0 ? '成長' : '下降';

      insights.push({
        id: `auto-sector-${iso3.toLowerCase()}-${sectorId}-${latestYear}`,
        category: 'sector_move',
        headline: `${ECONOMY_NAMES[iso3] ?? iso3}'s ${SECTOR_LABELS[sectorId] ?? sectorId} exports to the U.S. ${verb} ${Math.abs(yoy).toFixed(0)}% in ${latestYear}`,
        headlineZh: `${ECONOMY_NAMES_ZH[iso3] ?? iso3}對美${SECTOR_LABELS_ZH[sectorId] ?? sectorId}出口在${latestYear}年${zhVerb}${Math.abs(yoy).toFixed(0)}%`,
        body: `U.S. imports of ${SECTOR_LABELS[sectorId] ?? sectorId} goods from ${ECONOMY_NAMES[iso3] ?? iso3} ${verb} ${Math.abs(yoy).toFixed(1)}% year-over-year in ${latestYear}, from $${(prior / 1e9).toFixed(1)}B to $${(latest / 1e9).toFixed(1)}B. Source: UN Comtrade.`,
        bodyZh: `${latestYear}年美國自${ECONOMY_NAMES_ZH[iso3] ?? iso3}進口${SECTOR_LABELS_ZH[sectorId] ?? sectorId}商品年${zhVerb}${Math.abs(yoy).toFixed(1)}%，從${(prior / 1e9).toFixed(1)}億美元${yoy > 0 ? '增至' : '降至'}${(latest / 1e9).toFixed(1)}億美元。資料來源：聯合國商品貿易統計資料庫。`,
        metric: `${yoy >= 0 ? '+' : ''}${yoy.toFixed(0)}%`,
        metricDirection: dir,
        relatedEconomies: [iso3],
        relatedSectors: [sectorId],
        dataYear: latestYear,
        isAutoGenerated: true,
      });
    }
  }

  // 3. Taiwan lens: semiconductor share shift
  const twBase = sectorShare('TWN', 'semiconductors', baseYear);
  const twLatest = sectorShare('TWN', 'semiconductors', latestYear);
  const twPp = twLatest - twBase;
  if (twBase > 0 && Math.abs(twPp) > 0.5) {
    const dir = twPp > 0 ? ('up' as const) : ('down' as const);
    const verb = twPp > 0 ? 'rose' : 'fell';
    const zhVerb = twPp > 0 ? '上升' : '下降';

    insights.push({
      id: `auto-taiwan-semicon-${latestYear}`,
      category: 'taiwan_lens',
      headline: `Taiwan's share of U.S. semiconductor imports ${verb} by ${Math.abs(twPp).toFixed(1)}pp since ${baseYear}`,
      headlineZh: `台灣在美國半導體進口的市佔率自${baseYear}年${zhVerb}${Math.abs(twPp).toFixed(1)}個百分點`,
      body: `Taiwan's share of tracked U.S. semiconductor imports moved from ${twBase.toFixed(1)}% in ${baseYear} to ${twLatest.toFixed(1)}% in ${latestYear} (${twPp >= 0 ? '+' : ''}${twPp.toFixed(1)}pp). Covers HS 8541, 8542, 8471, 8473. Source: UN Comtrade.`,
      bodyZh: `台灣在美國受追蹤半導體進口（HS 8541/8542/8471/8473）中的佔比自${baseYear}年${twBase.toFixed(1)}%${zhVerb}至${latestYear}年${twLatest.toFixed(1)}%（${twPp >= 0 ? '+' : ''}${twPp.toFixed(1)}pp）。資料來源：聯合國商品貿易統計資料庫。`,
      metric: `${twPp >= 0 ? '+' : ''}${twPp.toFixed(1)}pp`,
      metricDirection: dir,
      relatedEconomies: ['TWN'],
      relatedSectors: ['semiconductors'],
      dataYear: latestYear,
      isAutoGenerated: true,
    });
  }

  // 4. Trend signal: consistent direction for 3+ consecutive years
  for (const iso3 of Object.values(PARTNERS)) {
    for (const sectorId of Object.keys(SECTORS)) {
      const yearsWithData = allYears.filter(y => psvt(iso3, sectorId, y) > 0);
      if (yearsWithData.length < 4) continue;

      const tail = yearsWithData.slice(-4);
      const vals = tail.map(y => psvt(iso3, sectorId, y));
      const dirs = vals.slice(1).map((v, i) => Math.sign(v - vals[i]!));
      const allUp = dirs.every(d => d > 0);
      const allDown = dirs.every(d => d < 0);
      if (!allUp && !allDown) continue;

      const streakDir = allUp ? ('up' as const) : ('down' as const);
      const verb = allUp ? 'risen' : 'fallen';
      const zhVerb = allUp ? '連續成長' : '連續下降';

      insights.push({
        id: `auto-trend-${iso3.toLowerCase()}-${sectorId}-${latestYear}`,
        category: 'trend_signal',
        headline: `${ECONOMY_NAMES[iso3] ?? iso3}'s ${SECTOR_LABELS[sectorId] ?? sectorId} exports to the U.S. have ${verb} for ${dirs.length} consecutive years`,
        headlineZh: `${ECONOMY_NAMES_ZH[iso3] ?? iso3}對美${SECTOR_LABELS_ZH[sectorId] ?? sectorId}出口已${zhVerb}${dirs.length}年`,
        body: `U.S. imports of ${SECTOR_LABELS[sectorId] ?? sectorId} goods from ${ECONOMY_NAMES[iso3] ?? iso3} moved in the same direction for ${dirs.length} consecutive years (${tail[0]}–${tail[tail.length - 1]}). Source: UN Comtrade.`,
        bodyZh: `美國自${ECONOMY_NAMES_ZH[iso3] ?? iso3}進口${SECTOR_LABELS_ZH[sectorId] ?? sectorId}商品已連續${dirs.length}年朝同方向變動（${tail[0]}–${tail[tail.length - 1]}）。資料來源：聯合國商品貿易統計資料庫。`,
        metric: `${dirs.length} yrs`,
        metricDirection: streakDir,
        relatedEconomies: [iso3],
        relatedSectors: [sectorId],
        dataYear: latestYear,
        isAutoGenerated: true,
      });
    }
  }

  // 5. Anomaly: direction reversal in latest year (min ±15% magnitude)
  for (const iso3 of Object.values(PARTNERS)) {
    for (const sectorId of Object.keys(SECTORS)) {
      const y3 = latestYear - 2;
      const y2 = latestYear - 1;
      const y1 = latestYear;
      const v3 = psvt(iso3, sectorId, y3);
      const v2 = psvt(iso3, sectorId, y2);
      const v1 = psvt(iso3, sectorId, y1);
      if (v3 === 0 || v2 === 0 || v1 === 0) continue;

      const priorDir = Math.sign(v2 - v3);
      const latestDir = Math.sign(v1 - v2);
      if (priorDir === 0 || latestDir === 0 || priorDir === latestDir) continue;

      const yoyPct = ((v1 - v2) / v2) * 100;
      if (Math.abs(yoyPct) < 15) continue;

      const dir = latestDir > 0 ? ('up' as const) : ('down' as const);
      const prior3verb = priorDir > 0 ? 'rising' : 'falling';
      const latestVerb = latestDir > 0 ? 'increased' : 'decreased';
      const zhLatestVerb = latestDir > 0 ? '轉升' : '轉降';

      insights.push({
        id: `auto-anomaly-${iso3.toLowerCase()}-${sectorId}-${latestYear}`,
        category: 'anomaly',
        headline: `${ECONOMY_NAMES[iso3] ?? iso3}'s ${SECTOR_LABELS[sectorId] ?? sectorId} exports to the U.S. reversed direction in ${y1}`,
        headlineZh: `${ECONOMY_NAMES_ZH[iso3] ?? iso3}對美${SECTOR_LABELS_ZH[sectorId] ?? sectorId}出口在${y1}年出現趨勢逆轉`,
        body: `After ${prior3verb} in ${y2}, U.S. imports of ${SECTOR_LABELS[sectorId] ?? sectorId} goods from ${ECONOMY_NAMES[iso3] ?? iso3} ${latestVerb} ${Math.abs(yoyPct).toFixed(1)}% in ${y1}. Source: UN Comtrade.`,
        bodyZh: `在${y2}年${priorDir > 0 ? '上升' : '下降'}後，美國自${ECONOMY_NAMES_ZH[iso3] ?? iso3}進口${SECTOR_LABELS_ZH[sectorId] ?? sectorId}商品在${y1}年${zhLatestVerb}${Math.abs(yoyPct).toFixed(1)}%。資料來源：聯合國商品貿易統計資料庫。`,
        metric: `${yoyPct >= 0 ? '+' : ''}${yoyPct.toFixed(0)}%`,
        metricDirection: dir,
        relatedEconomies: [iso3],
        relatedSectors: [sectorId],
        dataYear: latestYear,
        isAutoGenerated: true,
      });
    }
  }

  return insights;
}

// ── Main ───────────────────────────────────────────────────────────────────────

async function main() {
  // ── API key check ──────────────────────────────────────────────────────────
  const apiKey = process.env.COMTRADE_API_KEY;
  if (!apiKey) {
    console.error('\nError: COMTRADE_API_KEY is not set.\n');
    console.error('Set it before running:');
    console.error('  export COMTRADE_API_KEY=your_key_here\n');
    console.error('Get a free key at: https://comtradeapi.un.org\n');
    process.exit(1);
  }

  console.log('UN Comtrade Data Pipeline');
  console.log('─────────────────────────────────────────────────');

  // ── Load and back up existing data ────────────────────────────────────────
  const existing = readJson<TradeFlow[]>(TRADE_FLOWS_PATH, []);
  const existingKeys = new Set(
    existing.map(f => `${f.year}:${f.reporter}:${f.partner}:${f.sectorId}:${f.hsCode}`),
  );

  if (existing.length > 0) {
    const backupPath = TRADE_FLOWS_PATH.replace('.json', `.backup-${Date.now()}.json`);
    fs.copyFileSync(TRADE_FLOWS_PATH, backupPath);
    console.log(`Backed up ${existing.length} existing records → ${path.basename(backupPath)}`);
  }

  // ── Fetch loop ─────────────────────────────────────────────────────────────
  const newFlows: TradeFlow[] = [];
  let requestCount = 0;
  let skipCount = 0;
  let errorCount = 0;
  const failures: string[] = [];

  outerLoop: for (const [partnerCode, iso3] of Object.entries(PARTNERS)) {
    for (const [sectorId, sector] of Object.entries(SECTORS)) {
      for (const year of YEARS) {
        const allCached = sector.hsCodes.every(hs =>
          existingKeys.has(`${year}:${REPORTER_ISO3}:${iso3}:${sectorId}:${hs}`),
        );

        if (allCached) {
          skipCount++;
          continue;
        }

        if (requestCount >= REQUEST_LIMIT) {
          console.warn(`\nReached ${REQUEST_LIMIT}-request daily limit. Stopping early.`);
          break outerLoop;
        }

        console.log(`  Fetching: USA imports from ${iso3} · ${sectorId} · ${year}`);
        requestCount++;

        try {
          await sleep(DELAY_MS);
          const records = await fetchComtrade(partnerCode, sector.hsCodes, year, apiKey);
          const flows = toTradeFlows(records, sectorId, iso3);
          newFlows.push(...flows);
          console.log(`    ✓ ${flows.length} record${flows.length !== 1 ? 's' : ''}`);
        } catch (err) {
          errorCount++;
          const msg = `${iso3}/${sectorId}/${year}: ${err instanceof Error ? err.message : String(err)}`;
          failures.push(msg);
          console.error(`    ✗ ${msg}`);
        }
      }
    }
  }

  // ── Fallback if nothing was fetched and nothing existed ────────────────────
  if (newFlows.length === 0 && existing.length === 0) {
    console.warn('\nNo data fetched from API. Checking for fallback data...');
    try {
      const fb = readJson<{ _metadata: unknown; data: TradeFlow[] }>(
        FALLBACK_PATH,
        { _metadata: null, data: [] },
      );
      if (fb.data.length > 0) {
        console.warn(
          `  ⚠ Using fallback data (${fb.data.length} records). Values are approximate — not for production.\n`,
        );
        newFlows.push(...fb.data);
      } else {
        console.warn('  No fallback data found. trade-flows.json will remain empty.');
      }
    } catch {
      console.warn('  Could not read fallback-data.json.');
    }
  }

  // ── Merge ──────────────────────────────────────────────────────────────────
  const merged = [...existing];
  for (const f of newFlows) {
    const key = `${f.year}:${f.reporter}:${f.partner}:${f.sectorId}:${f.hsCode}`;
    if (!existingKeys.has(key)) {
      merged.push(f);
      existingKeys.add(key);
    }
  }

  const enriched = enrichFlows(merged);
  writeJson(TRADE_FLOWS_PATH, enriched);
  console.log(`\nWrote ${enriched.length} records → trade-flows.json`);

  // ── Update economies.json ──────────────────────────────────────────────────
  updateEconomies(enriched);

  // ── Generate insights and merge with manual briefing ──────────────────────
  const autoInsights = generateInsights(enriched);
  const existingBriefing = readJson<BriefingInsight[]>(BRIEFING_PATH, []);
  const manualInsights = existingBriefing.filter(i => !i.isAutoGenerated);
  const mergedBriefing = [
    ...manualInsights,
    ...autoInsights.filter(a => !manualInsights.some(m => m.id === a.id)),
  ];
  writeJson(BRIEFING_PATH, mergedBriefing);
  console.log(
    `Wrote ${mergedBriefing.length} insights → briefing.json` +
      ` (${manualInsights.length} manual, ${autoInsights.length} auto-generated)`,
  );

  // ── Summary ────────────────────────────────────────────────────────────────
  const coveredYears = [...new Set(enriched.map(f => f.year))].sort((a, b) => a - b);
  const coveredPartners = [...new Set(enriched.map(f => f.partner))].sort();

  console.log('\n── Summary ──────────────────────────────────────');
  console.log(`  Total records  : ${enriched.length}`);
  console.log(`  New records    : ${newFlows.length}`);
  console.log(`  Skipped (cache): ${skipCount}`);
  console.log(`  API requests   : ${requestCount}`);
  console.log(`  Errors         : ${errorCount}`);
  console.log(`  Years          : ${coveredYears.join(', ') || 'none'}`);
  console.log(`  Partners       : ${coveredPartners.join(', ') || 'none'}`);
  if (failures.length > 0) {
    console.log('\n  Failed requests:');
    failures.forEach(f => console.log(`    - ${f}`));
  }
  console.log('─────────────────────────────────────────────────\n');
}

main().catch(err => {
  console.error('\nFatal error:', err instanceof Error ? err.message : err);
  process.exit(1);
});
